name: Container Security Scan

on:
  registry_package:

jobs:
  container_scan:
    name: Container Scan
    
    runs-on: ubuntu-20.04
    
    steps:
      - name: Expose Event/Workflow Details
        uses: actions/github-script@v2
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
            console.log(JSON.stringify(process.env, null, 2));

      - name: Checkout Sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Docker login to Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u "<token>" --password-stdin
          
      - name: Perform Container Scan
        id: container_scan
        uses: anchore/scan-action@master
        with:
          image-reference: docker.pkg.github.com/${{ github.repository }}/${{ github.event.registry_package.name }}:${{ github.event.registry_package.package_version.version }}
          debug: true
          acs-report-enable: true
          acs-report-severity-cutoff: High

      - name: Display SARIF Report Data
        run: cat results.sarif

      - name: Upload Anchore Scan SARIF Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif